version: 2.0
jobs: 
  One:
    docker:
    - image: circleci/php
    steps:
    - checkout 
    - run: echo "Job One !!!"
        
  Two:
    docker:
    - image: circleci/php
    steps:
    - checkout 
    - run: echo "Job Two !!!"

workflows:
  version: 2  
  one_two:
    jobs:
     - One
     - Two

  
